site_name: is-a.dev Docs
site_url: https://www.is-a.dev/docs/
repo_url: https://github.com/is-a-dev/docs
edit_uri: blob/main/src/docs
site_description: Documentation for is-a.dev

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/banner.png
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Cloudflare Pages: cloudflare-pages/index.md
  - DanBot Hosting: dbh/index.md
  - Discord Domain Verification: discord-verification/index.md
  - Domain Structure: domain-structure/index.md
  - FAQ: faq/index.md
  - GitHub Pages: github-pages/index.md
  - GitHub Pages Domain Verification: github-pages-verification/index.md
  - Hashnode Blog: hashnode/index.md
  - ImprovMX: improvmx/index.md
  - Netlify: netlify/index.md
  - Other Services: other/index.md
  - Railway: railway/index.md
  - Render: render/index.md
  - Replit: replit/index.md
  - Resources: resources/index.md
  - Vercel: vercel/index.md

