site_name: is-a.dev Docs

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/banner.png
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Domain Structure: domain_structure/index.md
  - Cloudflare Pages: cloudflare_pages/index.md
  - Delete Your Domain: delete_domain/index.md
  - Discord Domain Verification: discord_verification/index.md
  - Edit Your Domain: edit_domain/index.md
  - GitHub Pages: github_pages/index.md
  - GitHub Pages Domain Verification: github_pages_verification/index.md
  - Hashnode Blog: hashnode/index.md
  - Railway: railway/index.md
  - Replit: replit/index.md
  - Other Services: other/index.md
